format ="""
$username$directory$all$character
"""

[username]
style_user = "green"
style_root = "black bold"
format = "[キアラン in ]($style)"
show_always = true

[directory]
style ="gray"
truncation_length = 1
truncation_symbol = "…/"

[character]
format ="$symbol"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[battery]
disabled = true
