format ="""
$username$directory$all$character
"""

[username]
style_user = "gray"
style_root = "black bold"
format = "[キアラン in ]($style)"
show_always = true

[directory]
style ="gray"

[character]
format ="$symbol"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[line_break]
disabled = true